services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=datapet'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
    volumes:
        - 'postgres:/var/lib/postgresql/data'
volumes:
    postgres:

